config/routes.rb
Rails.application.routes.draw do

 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")

  root 'users#new'
    resources :tasks
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
   
    get '/login', to: 'sessions#new'
    post "/login", to: "sessions#create"  
    delete "/logout", to: "sessions#destroy",as:"logout"
   
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :tasks
  validates :username, presence: true
  validates :email,presence:true
 validates :password, length: { in: 6..12 } 
 has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
    if @user
      redirect_to tasks_path
  end 
  def create
     @user = User.find_by(email: params[:email])
       if @user && @user.authenticate(params[:password])
         session[:user_id] = @user.id
          redirect_to tasks_path(@user.id),notice: 'Logged in successfully.'
       else
         flash[:alert] = 'Invalid email or password'
         redirect_to '/login'
       end
   end
 
   def destroy
     session[:user_id] = nil
     flash[:notice]="logged out"
     redirect_to "/login"
   end
end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def index
    @tasks = Task.where(user_id: session[:user_id])
  end
  def show
    @task = Task.find(params[:id])
  end
  def new
    @task = Task.new
  end
  def create
    @task = Task.where(user_id: session[:user_id]).new(task_params)
    if @task.save
      redirect_to tasks_path
      else
        render :new, status: :unprocessable_entity
        end
end
def edit
  @task = Task.find(params[:id])
end

def update
  @task =Task.find(params[:id])

  if @task.update(task_params)
    redirect_to @task
  else
    render :edit, status: :unprocessable_entity
  end
end
def destroy
  @task = Task.find(params[:id])
  @task.destroy

  redirect_to root_path, status: :see_other
end
private
def task_params
  params.require(:task).permit(:title, :description, :status)

end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #  skip_before_action :authorize, only :[:new, :create] 

  def new
   @user = User.new
  end
  def create
   @user = User.new(user_params)
    if @user.save 
     redirect_to login_path,notice: "User created successfully"
    else
      render :new
      flash.now[:error] = @user.errors.full_messages.to_sentence
    end
  end
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Taskmanagement" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <p class="notice" ><%=notice%></p>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partial/_header.html.erb
<nav class="navbar">
    <div class="navbar-left">
      <h1 class="navbar-title">Task Management</h1>
    </div>

      <div class="navbar-right"> 
      <% if session[:user_id] %>
      <% @user= User.find_by(id: session[:user_id])%>
           <p class="welcome-message">Welcome, <%= @user.email %> </p>
       <%= button_to 'Log Out', "/logout", method: :delete, form: { class: 'logout-form' } %>
             <%=button_to "home","/tasks",method: :get %>
         </div>
    <% end %>
  </nav>

app/views/tasks/_form.html.erb
<%= form_with model: task do |form| %>
  <div class="field">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
  </div>
  <div>
  <%= form.label :status %><br>
  <%= form.text_area :status %><br>
</div>
  <div class="field">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<header><%= render partial: 'partial/header'%></header>
<div class="container">
<h1>Edit Task</h1>

<%= render "form", task: @task%>
</div>

app/views/tasks/index.html.erb
<header><%= render partial: 'partial/header'%></header>
<div class="container">
<% if @tasks.any? %>
<ul>

<% @tasks.each do |task| %>
  <li><%= link_to task.title,task %></li>
  <%end%>
  <%end%>
</ul>
<%= link_to "New Task", new_task_path %>

</div>

app/views/tasks/new.html.erb
<header><%= render partial: 'partial/header'%></header>
<div class="container">
<h1>Add a new task</h1>

<%= render "form", task: @task %>
</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.description%></p>
<p><%= @task.status%></p>
<ul>
  <li><%= link_to "Edit", edit_task_path(@task) %></li>
  <li><%= link_to "Destroy", task_path(@task), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
  <%=button_to "home","/tasks",method: :get %>
</ul>

app/views/users/new.html.erb
<div class="form-container">
  <h1>Sign Up</h1>
  <div class="form-box">
    <%= form_with(model: @user, url: signup_path, local: false) do |f| %>
      <div class="form-group">
        <%= f.label :username %><br/>
        <%= f.text_field :username, class: "form-control" %>
      <div class="form-group">
        <%= f.label :email %><br/>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %><br/>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Sign Up", class: "btn btn-primary" %>
      </div>
      <div class="already-user">
      <p>Already a user? <%= link_to 'Login here', login_path %></p>
    </div>
    <% end %>
  </div>
</div>
 
 